# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1367, 721)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-151, -20, 2000, 880))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("E:\JARVIS\Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 516, 331))
        self.bg_2.setStyleSheet("background-color: rgb(16, 178, 214)")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(545, 10, 516, 331))
        self.bg_3.setStyleSheet("background-color: rgb(16, 178, 214)")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(20, 20, 496, 311))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("E:\JARVIS\Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(555, 20, 495, 311))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("E:\JARVIS\live.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(-180, 270, 671, 491))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("E:\JARVIS\__1.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(10, 360, 351, 331))
        self.bg_4.setText("")
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(1090, 10, 261, 211))
        self.bg_5.setStyleSheet("background-color: rgb(16, 178, 214)")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(1100, 20, 241, 191))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("E:\JARVIS\Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(1090, 550, 261, 71))
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("E:\JARVIS\gggf.jpg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(1090, 465, 261, 71))
        self.bg_8.setText("")
        self.bg_8.setPixmap(QtGui.QPixmap("E:\JARVIS\gggf.jpg"))
        self.bg_8.setScaledContents(True)
        self.bg_8.setObjectName("bg_8")
        self.Text_Day = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Day.setGeometry(QtCore.QRect(1170, 565, 261, 71))
        self.Text_Day.setStyleSheet("Background-color: Transparent;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Day.setObjectName("Text_Day")
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(1123, 482, 261, 61))
        self.Text_Date.setStyleSheet("Background-color: Transparent;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Date.setObjectName("Text_Date")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1100, 242, 241, 50))
        self.pushButton_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 24pt \"Courier New\";\n"
"")
        self.pushButton_start.setObjectName("pushButton_start")
        self.bg_9 = QtWidgets.QLabel(self.centralwidget)
        self.bg_9.setGeometry(QtCore.QRect(1090, 235, 261, 122))
        self.bg_9.setStyleSheet("background-color: rgb(16, 178, 214)")
        self.bg_9.setText("")
        self.bg_9.setObjectName("bg_9")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(1100, 300, 241, 50))
        self.pushButton_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 24pt \"Courier New\";\n"
"")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_yt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yt.setGeometry(QtCore.QRect(445, 520, 151, 51))
        self.pushButton_yt.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_yt.setObjectName("pushButton_yt")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(625, 520, 151, 51))
        self.pushButton_chrome.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(810, 520, 151, 51))
        self.pushButton_whatsapp.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(1090, 635, 261, 71))
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("E:\JARVIS\gggf.jpg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time.setGeometry(QtCore.QRect(1135, 652, 261, 71))
        self.Text_Time.setStyleSheet("Background-color: Transparent;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 255);\n"
"border-radius: none;")
        self.Text_Time.setObjectName("Text_Time")
        self.bg_1.raise_()
        self.Gif_3.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.bg_4.raise_()
        self.bg_5.raise_()
        self.Gif_4.raise_()
        self.bg_7.raise_()
        self.bg_8.raise_()
        self.Text_Day.raise_()
        self.Text_Date.raise_()
        self.bg_9.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_yt.raise_()
        self.pushButton_chrome.raise_()
        self.pushButton_whatsapp.raise_()
        self.bg_6.raise_()
        self.Text_Time.raise_()
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        self.Text_Day.setHtml(_translate("JarvisUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Text_Date.setHtml(_translate("JarvisUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_start.setText(_translate("JarvisUI", "Start"))
        self.pushButton_exit.setText(_translate("JarvisUI", "Exit"))
        self.pushButton_yt.setText(_translate("JarvisUI", "YouTube"))
        self.pushButton_chrome.setText(_translate("JarvisUI", "Chrome"))
        self.pushButton_whatsapp.setText(_translate("JarvisUI", "WhatsApp"))
        self.Text_Time.setHtml(_translate("JarvisUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
